name: Default
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Checkout
        uses: actions/checkout@v3

      - name: remove golangci from precommit-configuration
        run: |
          sed -i 's/.*id: golangci-lint//' .pre-commit-config.yaml
          sed -i '/^\s*$/d' .pre-commit-config.yaml

      - uses: pre-commit/action@v3.0.0
        continue-on-error: true

      - name: Build
        run: make all

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md

      - uses: rhysd/changelog-from-release/action@v2
        if: steps.semrel.outputs.version != ''
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
